//! Regression test for the `switchyard host` CLI surface.
//!
//! This specifically guards against clap parser panics caused by defining a
//! custom `help` subcommand alongside clap's autogenerated help subcommand.

use std::process::Command;

#[test]
fn host_help_subcommand_does_not_panic() {
    let output = Command::new(env!("CARGO_BIN_EXE_switchyard"))
        .args(["host", "help"])
        .output()
        .expect("failed to run switchyard host help");

    assert!(
        output.status.success(),
        "host help should succeed.\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("\"protocol\": \"hyard_v2\""),
        "host help should print HYARD protocol JSON. stdout:\n{stdout}",
    );
}
