//! Regression test for the `switchyard host` CLI surface.
//!
//! This specifically guards against clap parser panics caused by defining a
//! custom `help` subcommand alongside clap's autogenerated help subcommand.

use std::process::Command;

#[test]
fn host_help_subcommand_does_not_panic() {
    let output = Command::new(env!("CARGO_BIN_EXE_switchyard"))
        .args(["host", "help"])
        .output()
        .expect("failed to run switchyard host help");

    assert!(
        output.status.success(),
        "host help should succeed.\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("\"protocol\": \"hyard_v2\""),
        "host help should print HYARD protocol JSON. stdout:\n{stdout}",
    );
}

#[test]
fn host_inbox_help_lists_callback_options() {
    let output = Command::new(env!("CARGO_BIN_EXE_switchyard"))
        .args(["host", "inbox", "--help"])
        .output()
        .expect("failed to run switchyard host inbox --help");

    assert!(
        output.status.success(),
        "host inbox --help should succeed.\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("--session"));
    assert!(stdout.contains("--resume-latest"));
    assert!(stdout.contains("--mark-read"));
    assert!(stdout.contains("--consume"));
}

#[test]
fn host_watch_help_lists_callback_options() {
    let output = Command::new(env!("CARGO_BIN_EXE_switchyard"))
        .args(["host", "watch", "--help"])
        .output()
        .expect("failed to run switchyard host watch --help");

    assert!(
        output.status.success(),
        "host watch --help should succeed.\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("--session"));
    assert!(stdout.contains("--resume-latest"));
    assert!(stdout.contains("--timeout-sec"));
    assert!(stdout.contains("--mark-read"));
    assert!(stdout.contains("--consume"));
}

#[test]
fn host_delegate_help_lists_session_option() {
    let output = Command::new(env!("CARGO_BIN_EXE_switchyard"))
        .args(["host", "delegate", "--help"])
        .output()
        .expect("failed to run switchyard host delegate --help");

    assert!(
        output.status.success(),
        "host delegate --help should succeed.\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("--provider"));
    assert!(stdout.contains("--task"));
    assert!(stdout.contains("--session"));
    assert!(stdout.contains("--wait-sec"));
}

#[test]
fn host_resume_help_lists_callback_and_message_options() {
    let output = Command::new(env!("CARGO_BIN_EXE_switchyard"))
        .args(["host", "resume", "--help"])
        .output()
        .expect("failed to run switchyard host resume --help");

    assert!(
        output.status.success(),
        "host resume --help should succeed.\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("--session"));
    assert!(stdout.contains("--resume-latest"));
    assert!(stdout.contains("--message"));
    assert!(stdout.contains("--callbacks"));
}

#[test]
fn host_follow_help_lists_session_and_timeout_options() {
    let output = Command::new(env!("CARGO_BIN_EXE_switchyard"))
        .args(["host", "follow", "--help"])
        .output()
        .expect("failed to run switchyard host follow --help");

    assert!(
        output.status.success(),
        "host follow --help should succeed.\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("--session"));
    assert!(stdout.contains("--resume-latest"));
    assert!(stdout.contains("--timeout-sec"));
    assert!(stdout.contains("--forever"));
}
